import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import type { StructuredJD } from '../jd/index.ts';
import { JDSchema } from '../jd/index.ts';
import { RankConfigSchema, scoreJob } from './rank.ts';

/**
 * Replay parity vs v0 `scripts/pipeline/rank.js` (P7 rank-parity fix).
 *
 * v0 scores 5 axes out of 100 — skills, title, seniority, work-type+tz,
 * YoE — and so does this module now (see rank.ts's module comment for how
 * each axis maps onto StructuredJD, and why YoE alone stays fixed at its
 * neutral credit: v2 models no JD-side YoE requirement and no
 * candidate-side current YoE at all).
 *
 * Every fixture row below was generated by calling the real v0 `scoreJob()`
 * (via a one-off script under /private/tmp, not checked in) with
 * `years_of_experience: null` on every row — the same "no requirement"
 * shape v0 itself treats as a neutral signal (rank.js:154-156), and the
 * only YoE shape v2 can ever produce (it has no field to carry a real
 * requirement). That makes `v0FullScore` an honest, no-offset parity target
 * for v2's `scoreJob()`: every row exercises the same 5 axes, on the same
 * terms, in both trees.
 *
 * Per the task spec, every row here carries NO soft-fail verdicts (no
 * `evaluation` field at all) — the soft-verdict penalty is a v2-only
 * behavior with no v0 counterpart, and is covered separately in
 * rank.test.ts so it doesn't muddy this parity comparison.
 */

const cfg = RankConfigSchema.parse({
  skills: {
    primary: ['React', 'TypeScript', 'Design Systems'],
    secondary: ['GraphQL', 'Node.js'],
  },
  title: {
    domainKeywords: ['Frontend', 'Backend'],
  },
  seniority: {
    targets: ['Staff', 'Senior'],
  },
  location: {
    homeCities: ['Chennai'],
    acceptableTimezones: ['APAC'],
    borderlineTimezones: ['EMEA'],
  },
});

type ReplayRow = {
  name: string;
  input: unknown;
  v0FullScore: number;
  v0Reasons: string[];
};

const fixturePath = new URL('./fixtures/replay.json', import.meta.url);
const replay: ReplayRow[] = JSON.parse(readFileSync(fixturePath, 'utf8'));

test('replay fixture has 8 rows', () => {
  assert.equal(replay.length, 8);
});

test('replay fixture spans all three excitement bands', () => {
  const bands = replay.map((row) =>
    row.v0FullScore >= 85 ? 'high' : row.v0FullScore >= 65 ? 'mid' : 'low',
  );
  assert.ok(bands.includes('high'), 'no fixture row lands in the >=85 Vera level band');
  assert.ok(bands.includes('mid'), 'no fixture row lands in the 65-84 Kandipa podu band');
  assert.ok(bands.includes('low'), 'no fixture row lands in the <65 Try panalam band');
});

test('every fixture row carries no soft-fail verdicts (clean parity baseline)', () => {
  for (const row of replay) {
    const jd = JDSchema.parse(row.input) as StructuredJD;
    assert.equal(
      jd.evaluation,
      undefined,
      `${row.name} must carry no evaluation/verdicts`,
    );
  }
});

for (const row of replay) {
  test(`replay parity: ${row.name}`, () => {
    const jd = JDSchema.parse(row.input) as StructuredJD;
    const { score } = scoreJob(jd, cfg);
    assert.equal(
      score,
      row.v0FullScore,
      `${row.name}: v2=${score} v0=${row.v0FullScore} — v0Reasons=${JSON.stringify(row.v0Reasons)}`,
    );
  });
}
